### ISSUE TITLE
error: each element of 'ext_modules' option must be an Extension instance or 2-tuple

### ISSUE THREAD

**Issue by cvondrick** [cvondrick/vatic#5]
Workaround: (need better solution)

Unfortunately, there is a weird bug/feature in the latest Ubuntu's
installation for how it handles Python extensions. I plan to implement
a workaround for vatic, but in the mean time, you can apply this
patch:

1) Edit /usr/lib/python2.7/distutils/command/build_ext.py
2) Find line 356, where it reads:

for i, ext in enumerate(extensions):

3) After that line, add a new line that just says "continue", so that
it looks like:

```
   for i, ext in enumerate(extensions):
       continue
       if isinstance(ext, Extension):
           continue                # OK! (assume type-checking done
                                   # by Extension constructor)
```

4) Save the file
5) Go to the pyvision directory and run: $ sudo python setup.py install

**Comment by johnyf** [comment]
Found this while searching for a similar bug. For posterity, the relevant `setuptools` issue is: https://bitbucket.org/pypa/setuptools/issues/309/error-each-element-of-ext_modules-option
