### ISSUE TITLE
Interpolation issue- minimum frame change

### ISSUE THREAD

**Issue by kr-ish** [cvondrick/vatic#51]
It seems that interpolation only works correctly across 4 or more frames. If I want to get the right annotation, I have to jump ahead by at least 3 frames. This makes frame by frame correction difficult / impossible. This is a bigger problem when on object comes into frame - if frame by frame correction is attempted, the outside of view attributed is incorrectly interpolated. If anyone else who is facing this problem / knows how to fix it/ knows where to look to fix it could let me know, I would greatly appreciate it. Thanks!

**Comment by nileshgu** [comment]
Did you find a catch yet? I have recently reduced the frames per second of my video. I made a sub-video out of main video taking only every 10 frames. When I annotate the resulting sub-video, interpolation doesnt work fine and the bounding boxes around the object is always moving.

**Comment by 0wu** [comment]
for the "outside of view attributed is incorrectly interpolated". You may want to set the blow-radius=0 when "load" a task

**Comment by kr-ish** [comment]
^that's what I ended up doing finally
I fixed my outside attribute code by making it identical to the occluded code (removing the interpolation of that attribute using the estimate function), and set the blow-radius 1 so that interpolation of objects worked across one frame.
