### ISSUE TITLE
turkic setup --public-symlink does not work

### ISSUE THREAD

**Issue by yukinak** [cvondrick/vatic#67]
Hi,

I have a problem on running 
`turkic setup --public-symlink` returns an error
`Could not create symlink!`.

I think this makes an error on /var/log/apache2/error.log.
> [Sat Mar 04 16:40:48.626938 2017] [core:error] [pid 3857:tid 140653468055296] [client 127.0.0.1:56708] AH00037: Symbolic link not allowed or link target not accessible: /home/user/vatic-tool/vatic/public/frames/identifier, referer: http://localhost/?id=1&hitId=offline

I would appreciate any suggestion.
Thanks,

**Comment by yukinak** [comment]
Partially solved. 

Once deleted `/path/to/vatic/public/turkic`, 
then `turkic setup --public-symlink` worked.

`Created symblink /usr/local/lib/python2.7/dist-packages/turkic-0.2.5-py2.7.egg/turkic/public to /path/to/vatic/public/turkic`.

However, there is still an AH00037 error, so I cannot access to [http://localhost/?id=1&hitId=offline](http://localhost/?id=1&hitId=offline).

**Comment by yukinak** [comment]
Completely solved by changing a destination directory like this;
`turkic extract src.mp4 ~/work/dst/`

**Comment by stonycat** [comment]
@yukinak  hello, I meet the same problem as when I running `turkic setup --public-symlink`, but
I can't find sth. in the error log, can you tell me how can you solve it in details？ 
Thanks！

**Comment by yukinak** [comment]
@stonycat Can you remove the symbolic link of `/path/to/vatic/public/turkic`?
I think you cannot create new symlink on the existing symlink.

**Comment by stonycat** [comment]
@yukinak Thank you, I have an existing turkic link in the path to `vatic/public/.`  I didn't understand the error before.

**Comment by YangBain** [comment]
@yukinak I have the same problem. Could you help me for this problem? Thank you very much.
This is my 000-default:
WSGIDaemonProcess www-data
WSGIProcessGroup www-data

<VirtualHost *:80>
    ServerName localhost
    DocumentRoot /home/beans/vatic/vatic/public

    WSGIScriptAlias /server /home/beans/vatic/vatic/server.py
    CustomLog /var/log/apache2/access.log combined
</VirtualHost>
%%%%%%%%%%%%%%%%%%%%%%%
~/vatic/vatic$ turkic setup --public-symlink
Could not create symlink!

**Comment by yukinak** [comment]
@YangBain I think it's the same problem we discussed. Can you remove the symbolic link of /path/to/vatic/public/turkic?

**Comment by aseuteurideu** [comment]
@yukinak do you know why changing destination directory solve the problem? What was your previous destination directory?
